### ISSUE TITLE
Upgrade to JDK-14

### ISSUE THREAD

**Issue by AntonOellerer** [docu-tools-developers/jocument#5]
To be able to use the new `switch-case` expression, the project should be upgraded to the most recent JDK version

**Comment by AntonOellerer** [comment]
Blocking #6

**Comment by codecitizen** [comment]
@AntonOellerer resolved it by upgrading to Gradle 6.6.* snapshot, [read more here](https://github.com/gradle/gradle/issues/10248). Please review and merge if OK.
