### ISSUE TITLE
Detect language / Locale of template document from file via Apache POI

### ISSUE THREAD

**Issue by AntonOellerer** [docu-tools-developers/jocument#7]
Right now, the locale has to be specified in the document creation request.
It should be possible to figure out the locale from the Apache POI interface, which would make the `jocument` interface cleaner.

**Comment by codecitizen** [comment]
Found [this forum thread](http://apache-poi.1045710.n5.nabble.com/Finding-document-language-td5724126.html) where the user Timothy B. states that inherently documents have no "document level" language, since theoretically every paragraph / run (or cells in excel context) could be set to a different language.

[Here](https://poi.apache.org/apidocs/dev/org/apache/poi/xwpf/usermodel/XWPFRun.html#getLang--) you can see, that `XWPFRun` has a `.getLang` method.

We could write a helper/utility function, that iterates through all elements of a document and returns all distinct languages it found, maybe with a occurrence frequency.

**Comment by codecitizen** [comment]
Proposed a solution in eecf1b8

**Comment by AntonOellerer** [comment]
Seems reasonable, I found (this resoure) [https://thinktibits.blogspot.com/2014/07/read-write-metadata-excel-poi-example.html] showing how to read the metadata of documents, but when I tried to test it locally, nothing was set.

**Comment by AntonOellerer** [comment]
Two questions arise though:
* This code determines the locale based on the language tag, but is this really reliable?
* What do we do with the result, e.g. how do we decide on the final locale of the document?

**Comment by codecitizen** [comment]
I think it depends on the use case and we need to let the caller decide for a "localisation strategy". I see the cases:

1. The template is written multilingual with the intention of addressing multiple audiences (e.g. generating reports going to stakeholders in EU and US). Here the user wants to have different the localised placeholders based on the paragraph language. We have to assume here the user knows hot to properly localise paragraphs in their document.
2. The template is bound to one local, no matter what setting a paragraph has. In that case we should allow the user to specify a template local instance and if he doesn't fallback to:
  a. A document wide language setting (as in your link).
  b. The most frequently used language (number of paragraphs may not mean its the most frequent, rather paragraph length in one language / total length).
  c. The default locale of the current system.

So I would define a enum like:

```java
enum LocalisationStrategy {
  BY_PARAGRAPH, GLOABL
}
```

... and let the user specify how to go for it.

**Comment by AntonOellerer** [comment]
That sounds good, although I think that if the user has to select `GLOBAL`, he can just set the locale by himself.
And wouldn't the `BY_PARAGRAPH` solution have bigger implication on the whole project?

**Comment by codecitizen** [comment]
> And wouldn't the BY_PARAGRAPH solution have bigger implication on the whole project?

You mean refactoring wise? The localisation strategy has to happen probably in the Word Generator.

**Comment by AntonOellerer** [comment]
Can be accepted as solution in my opinion

**Comment by AntonOellerer** [comment]
According to the [Apache HPSF API Documentation](https://poi.apache.org/apidocs/dev/org/apache/poi/hpsf/DocumentSummaryInformation.html#getLanguage--), the language field of document is usually unset, empty or `null`

**Comment by AntonOellerer** [comment]
Way to move forward:
* For generation, use locale of (first) run in paragraph
* If there is no run locale, fallback is standard locale, which is most comman locale of document
